230320/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    # ''에 매칭되면(articles/에 들어오면) views.index에서 처리해줘
    path('',views.index, name='index'),
    # 숫자가 들어오면 id로 받아서 views.detail에서 처리해줘 
    path('<int:pk>/',views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/update/', views.update, name='update'),
    
]

230320/articles/models.py
from django.db import models

# Create your models here.

# 타이틀, 내용 필요
class Article(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # =>모델에 대한 변경사항 생겼으므로, makemigraitons & migrate 해주기  

    # 매직메서드 오버라이딩
    # 상위클래스 정의된 메서드와 동작을 달리 해주고 싶을 때 
    def __str__(self):
        return f'{self.id}번째 글 - {self.title}'

230320/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
# Create your views here.
def index(request):   
    articles = Article.objects.all()    # DB에서 모!든! Article 가져오기(articles)
    context = {'articles' : articles}   # context로 articles 넘겨주기 
    return render(request,'articles/index.html', context) # 두번째 파라미터에 템플릿 경로 넘겨주기(템플릿 만들어야 함)

def detail(request,pk):
    article = Article.objects.get(id=pk) # 한 개의 Article 조회(article)
    context = {'article':article}        # 한 개의 조회한 article context에 받아서 보내주기
    return render(request, 'articles/detail.html',context)

def new(request):               # 비어있는 form 화면 보여주면 됨
    return render(request,'articles/new.html')      

def create(request):   
    # [1] 사용자가 전송한 데이터(request) 가져온다        
    title = request.POST.get('title')     
    content = request.POST.get('content')  
    print(title,content)

    # [2] DB에 새로운 Article 저장한다
    # Article.objects.create(
    #     title=title,
    #     content=content
    # )

    # 데이터 저장 전 유효성 검사 위해 
    article = Article(title=title, content=content)
    article.save()


    # [3] 저장한 걸 index 페이지로 보낸다
    return redirect('articles:index') 


def delete(request,pk):
    article = Article.objects.get(pk=pk)    # 한 개의 Article 조회(article)
    article.delete()                        # 해당 article 삭제
    return redirect('articles:index')       # 그 결과값 반영한 index 페이지 찾아감 

def edit(request,pk):
    article = Article.objects.get(pk=pk)    # 한 개의 Article 조회(article)
    context = {'article':article}           # 조회한 article context에 받아서 보내주기
    return render(request, 'articles/edit.html', context)   # 템플릿 경로 넘겨주기

def update(request,pk):
    article = Article.objects.get(pk=pk)
    article.title = request.POST.get('title')
    article.content = request.POST.get('content')
    article.save()
    return redirect('articles:detail', pk= article.pk)

230320/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
    {% comment %} 
    화면에 보여질 부분---------------------------- {% endcomment %}
    <h1>DETAIL</h1>
    <hr>
    
    <p>글 제목 : {{article.title}}</p>
    <p>글 내용 : {{article.content}}</p>
    <p>생성시각 : {{article.created_at}}</p>
    <p>수정시각 : {{article.updated_at}}</p>
    <hr>

    {% comment %}--------------------------------
    뒤로가기 링크 만들기 {% endcomment %}
    <a href="{% url 'articles:index' %}">뒤로가기</a>

    {% comment %} 
    수정하기 링크 만들기 {% endcomment %}
    <a href="{% url 'articles:edit' article.pk %}">수정하기</a>

    {% comment %} 
    삭제 폼(버튼) 만들기
    action = 'submit 하면 어디로 보내지?' {% endcomment %}
    <form action="{% url 'articles:delete' article.pk %}">
        {% csrf_token %}
        <input type="submit" value='삭제하기'>
    </form>
{% endblock content %}


230320/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>글 수정하기</h1>
    <hr>

    <form action="{% url 'articles:update' article.pk %}" method = "POST">
        {% csrf_token %}
        <label for="title">제목</label>
        <input type="text" id ='title' name='title' value="{{article.title}}"><br>

        <label for="content">내용</label>
        <input type="text" id='content' name='content' value="{{article.content}}"><br>

        <input type="submit"> 
    </form>

    <hr>
    <a href="{% url 'articles:detail' article.pk %}">돌아가기</a>


{% endblock content %}



230320/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>INDEX</h1>
    <a href="{% url 'articles:new' %}">작성하기</a>
    <hr>
    {% for article in articles %}
        <p>글 번호: {{article.pk}}</p>
        {% comment %} 
        글 제목을 누르면 detail 들어갈 수 있게
        <p>글 제목: {{article.title}}</p>{% endcomment %}
        <p><a href="{% url 'articles:detail' article.pk %}">글 제목: {{article.title}}</a></p>
        <p>글 내용: {{article.content}}</p>
        <hr>
    {% endfor %}
{% endblock content %}


230320/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>새 글 작성 NEW</h1>
    <hr>

    {% comment %} 
    <form 태그>로 입력 창 만들기 
    action="(제출)누르면 어디로 보내지?를 적어주는 부분"{% endcomment %}
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        
        {% comment %} 
        제목(title) {% endcomment %}
        <label for="title">제목:</label>
        <input type="text" id="title" name="title"><br>

        {% comment %} 
        내용(content) {% endcomment %}
        <label for="content">내용:</label>
        <input type="text" id="content" name="content"><br>

        {% comment %} 
        제출(submit) {% endcomment %}
        <input type="submit">

    </form>

{% endblock content %}
