230316/django-pjt(230316)/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
]

230316/django-pjt(230316)/articles/models.py
from django.db import models

# Create your models here.

230316/django-pjt(230316)/articles/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'articles/index.html')

def throw(request):
    return render(request,'articles/throw.html')

def catch(request):
    message = request.GET.get('message')
    context = {
        'message' : message
    }
    return render(request,'articles/catch.html',context )

230316/django-pjt(230316)/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
<h1>Catch</h1>
<h2>보낸 데이터 : {{message}}</h2>
<a href="{% url 'articles:throw' %}">다시 데이터 보내러 가기</a>
{% endblock  %}

230316/django-pjt(230316)/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>여기는 인덱스입니다</h1>
{% endblock content %}

230316/django-pjt(230316)/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}

    <h1>Throw</h1>

    {% comment %} 
    action : 어디로 보낼래(url), method : 어떻게 보낼래
    메소드에 뭘 적지 않는다면 기본적으로 get형태 메소드
    {% endcomment %}
    <form action= "{% url 'articles:catch' %}" method="GET">
         {% comment %} for문 내용과 id 내용 같아야함(message) {% endcomment %}
         {% comment %} GET :  내가 작성한 데이터를 url 형태로  {% endcomment %}
         <label for="message">보내고 싶은 데이터 적기</label>
         <input type="text" id='message' name='message'>

        {% comment %} 제출 버튼 만들기 {% endcomment %}
        <input type="submit"> 
    </form>

{% endblock content %}